apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
  spec:
    selector:
      app: my-app
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP